### ISSUE TITLE
Invalid Scheduled Task Index results in Traceback

### ISSUE THREAD

**Issue by bartTC** [apppackio/apppack#33]
The instance has no scheduled tasks left, calling delete once more fails this way.

```
❯ apppack scheduled-tasks delete 1
⠧ panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/apppackio/apppack/app.(*App).DeleteScheduledTask(0x140003984e0, 0x0)
	/home/runner/work/apppack/apppack/app/app.go:938 +0x424
github.com/apppackio/apppack/cmd.glob..func55(0x10385eb80, {0x14000317080, 0x1, 0x3})
	/home/runner/work/apppack/apppack/cmd/scheduledTasks.go:136 +0x150
github.com/spf13/cobra.(*Command).execute(0x10385eb80, {0x14000317050, 0x3, 0x3})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:860 +0x640
github.com/spf13/cobra.(*Command).ExecuteC(0x10385df00)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x410
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
github.com/apppackio/apppack/cmd.Execute()
	/home/runner/work/apppack/apppack/cmd/root.go:80 +0x30
main.main()
	/home/runner/work/apppack/apppack/main.go:46 +0xd8```

**Comment by ipmb** [comment]
I think this should be a `>=`

https://github.com/apppackio/apppack/blame/7dce53daf36d02ad753c8c3c41ae0f91c24acb75/app/app.go#L1000

**Comment by bartTC** [comment]
Still running into this, like to bump it.
